In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('Predict Hair Fall.csv')
print(data.head())
data.describe()

       Id Genetics Hormonal Changes Medical Conditions  \
0  133992      Yes               No            No Data
1  148393       No               No             Eczema
2  155074       No               No         Dermatosis
3  118261      Yes              Yes           Ringworm
4  111915       No               No          Psoriasis

  Medications & Treatments Nutritional Deficiencies     Stress  Age  \
0                  No Data      Magnesium deficiency  Moderate   19
1              Antibiotics      Magnesium deficiency      High   43
2         Antifungal Cream        Protein deficiency  Moderate   26
3              Antibiotics        Biotin Deficiency   Moderate   46
4                 Accutane           Iron deficiency  Moderate   30

  Poor Hair Care Habits  Environmental Factors Smoking Weight Loss   Hair Loss
0                    Yes                   Yes      No           No          0
1                    Yes                   Yes      No           No          0
2                    Yes                   Yes      No          Yes          0
3                    Yes                   Yes      No           No          0
4                     No                   Yes     Yes           No          1

                  Id         Age   Hair Loss
count     999.000000  999.000000  999.000000
mean   153354.673674   34.188188    0.497497
std     25516.041985    9.377980    0.500244
min    110003.000000   18.000000    0.000000
25%    131867.500000   26.000000    0.000000
50%    152951.000000   34.000000    0.000000
75%    174969.000000   42.000000    1.000000
max    199949.000000   50.000000    1.000000

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Id                         999 non-null    int64
 1   Genetics                   999 non-null    object
 2   Hormonal Changes           999 non-null    object
 3   Medical Conditions         999 non-null    object
 4   Medications & Treatments   999 non-null    object
 5   Nutritional Deficiencies   999 non-null    object
 6   Stress                     999 non-null    object
 7   Age                        999 non-null    int64
 8   Poor Hair Care Habits      999 non-null    object
 9   Environmental Factors      999 non-null    object
 10  Smoking                    999 non-null    object
 11  Weight Loss                999 non-null    object
 12  Hair Loss                  999 non-null    int64
dtypes: int64(3), object(10)
memory usage: 101.6+ KB

In [4]:
data.columns, data.shape

(Index(['Id', 'Genetics', 'Hormonal Changes', 'Medical Conditions',
        'Medications & Treatments', 'Nutritional Deficiencies ', 'Stress',
        'Age', 'Poor Hair Care Habits ', 'Environmental Factors', 'Smoking',
        'Weight Loss ', 'Hair Loss'],
       dtype='object'),
 (999, 13))

In [5]:
final_data = data.drop('Id',axis=1)
print(final_data.columns)

Index(['Genetics', 'Hormonal Changes', 'Medical Conditions',
       'Medications & Treatments', 'Nutritional Deficiencies ', 'Stress',
       'Age', 'Poor Hair Care Habits ', 'Environmental Factors', 'Smoking',
       'Weight Loss ', 'Hair Loss'],
      dtype='object')

In [6]:
columns = ['Genetics','Environmental Factors','Smoking','Weight Loss ','Poor Hair Care Habits ','Hormonal Changes']
for column in columns:
    final_data[column] = final_data[column].map({'Yes': 1, 'No': 0})
final_data['Stress'] = final_data['Stress'].map({'High': 1.0, 'Moderate' : 0.5, 'Low': 0.0})   
final_data.head(2)

,Genetics,Hormonal Changes,Medical Conditions,Medications & Treatments,Nutritional Deficiencies,Stress,Age,Poor Hair Care Habits,Environmental Factors,Smoking,Weight Loss,Hair Loss
0,1,0,No Data,No Data,Magnesium deficiency,0.5,19,1,1,0,0,0
1,0,0,Eczema,Antibiotics,Magnesium deficiency,1.0,43,1,1,0,0,0

In [7]:
from sklearn.model_selection import train_test_split
X=final_data.drop('Hair Loss',axis=1)
Y=final_data['Hair Loss']
columns_to_encode = ['Medical Conditions', 'Medications & Treatments', 'Nutritional Deficiencies ']

for column in columns_to_encode:
    frequency_map = X[column].value_counts(normalize=True)
    X[column]=X[column].map(frequency_map)

X

,Genetics,Hormonal Changes,Medical Conditions,Medications & Treatments,Nutritional Deficiencies,Stress,Age,Poor Hair Care Habits,Environmental Factors,Smoking,Weight Loss
0,1,0,0.110110,0.002002,0.084084,0.5,19,1,1,0,0
1,0,0,0.069069,0.094094,0.084084,1.0,43,1,1,0,0
2,0,0,0.088088,0.094094,0.090090,0.5,26,1,1,0,1
3,1,1,0.069069,0.094094,0.099099,0.5,46,1,1,0,0
4,0,0,0.100100,0.102102,0.078078,0.5,30,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...
994,1,0,0.088088,0.116116,0.099099,0.0,33,1,1,1,1
995,1,1,0.110110,0.102102,0.090090,0.0,47,0,0,0,1
996,0,1,0.098098,0.110110,0.090090,0.5,20,1,0,1,1
997,0,1,0.092092,0.090090,0.099099,0.5,32,1,1,1,1
998,1,1,0.100100,0.090090,0.104104,0.0,34,0,1,0,0

In [8]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,train_size=0.7,test_size=0.3)

In [9]:
# Save the training set to a CSV file by combining X_train and Y_train
train_set = pd.concat([X_train, Y_train], axis=1)
train_set.to_csv('training_set.csv', index=False)

In [10]:
from sklearn.tree import DecisionTreeClassifier

model=DecisionTreeClassifier()
model.fit(X_train,Y_train)
model.score(X_train,Y_train)
model.score(X_test,Y_test)

0.5366666666666666

Save the trained model to a file

In [11]:
import pickle

# Save the trained model to a file
with open('prediction-ui/hair_loss_model.pkl', 'wb') as f:
    pickle.dump(model, f)